name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  permission_handler: ^11.3.1

  device_info_plus: ^11.1.0

  path_provider: ^2.1.4

  shared_preferences: ^2.3.2

  camera: ^0.11.0+2

  video_player: ^2.9.2

  font_awesome_flutter: ^10.7.0

  json_serializable: ^6.8.0

  google_maps_flutter: ^2.10.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  go_router: ^14.3.0

  flutter_webrtc: ^0.12.3

  uuid: ^4.5.1

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  equatable: ^2.0.5

  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1

  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
