name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  permission_handler: ^11.3.1

  device_info_plus: ^10.1.2

  path_provider: ^2.1.4

  shared_preferences: ^2.3.2

  camera: ^0.11.0+2

  video_player: ^2.9.2

  font_awesome_flutter: ^10.7.0

  json_serializable: ^6.8.0

  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.14.11
  google_maps_flutter_platform_interface: ^2.9.5
  flutter_plugin_android_lifecycle: ^2.0.23
  geolocator: ^13.0.2


  go_router: ^14.3.0

  stream_video_flutter: ^0.7.2
  stream_video: ^0.7.2
  stream_video_push_notification: ^0.7.2

  uuid: ^4.5.1

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  equatable: ^2.0.5

  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1

  #flutter_local_notifications: ^18.0.1

  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/memories.json
    - assets/json/news_articles.json
    - assets/json/profile_picture.json
    - assets/json/snapchat_mock_data.json
    - assets/json/map_data.json
