name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

  camera: ^0.11.0+2

  go_router: ^14.3.0

  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.1

  #stream_video_flutter: ^0.6.0

  equatable: ^2.0.5

  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
